version: "3.8"

services:
  gasolinera_app:
    build: .
    container_name: gasolinera_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://iasanz.synology.me:3306/iastillerog02_Gasolinera?ssl=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: alumno
      SPRING_DATASOURCE_PASSWORD: AlumnoSanz$1
      SPRING_APPLICATION_NAME: app_vet
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    restart: always
